[project]
name = "pdf2imageconverter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pdf2image>=1.17.0",
    "pyinstaller>=6.11.0",
    "rich>=13.9.3",
]
